baseURL = "https://developers.cloudflare.com/workers"
languageCode = "en-us"
title = "Cloudflare Workers Docs"
theme = "@cloudflare/hugo-cloudflare-docs"
themesDir = "node_modules"
description = "Cloudflare Workers lets you write JavaScript on the Edge"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
canonifyURLs = true
disableKinds = "taxonomyTerm"
ignoreFiles = [ "style/*", "CONTRIBUTING.md" ]
